version: '3.1'

services:
  server:
    image: "barumel/docker-astroneer-server:latest"
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      - "ASTRO_SERVER_PORT=${ASTRO_SERVER_PORT}"
      - "ASTRO_SERVER_NAME=${ASTRO_SERVER_NAME}"
      - "ASTRO_SERVER_PASSWORD=${ASTRO_SERVER_PASSWORD}"
      - "ASTRO_SERVER_OWNER_NAME=${ASTRO_SERVER_OWNER_NAME}"
      - "TZ=${TZ}"
    ports:
      - 8777:8777/tcp
      - 8777:8777/udp
    volumes:
     - astroneer:/astroneer
     - steamcmd:/steamcmd
     - wine:/wine
     - backup:/backup

volumes:
  astroneer:
  steamcmd:
  wine:
  backup:
